### ISSUE TITLE
Batch-importing student data, or connection to ILIAS

### ISSUE THREAD

**Issue by qwach** [Dudrie/Tutor-Management-System#1012]
# :ticket: Description
It's a little tedious to manually copy all the student names, their ILIAS user names, etc. and create the students one by one for each group. Alternatively either there could be a simple API (or UI button) for batch-importing a CSV or the like - seems there are some import-export functions already so doesn't seem too hard - or the website could directly connect to ILIAS' SOAP API to fetch data with no further user input.

**Comment by nk-coding** [comment]
For now csv import will be implemented.
Ilias API might be an option in the future, however I doubt that we will be able to get the matriculationNo, courseOfStudies (and maybe also the the email).
