### ISSUE TITLE
Passwords with special characters cause error

### ISSUE THREAD

**Issue by schurpl** [Dudrie/Tutor-Management-System#112]
When setting a password which contains special characters you are not able to log in anymore.

# :heavy_check_mark: Expected behaviour
Set Password with special characters afterwards i am able to log into my account.

# ⚡ Actual behaviour 
Set password which contains special characters. System confirms my password change.
After logout.
Try to login with new password system says username and password don't match.

# :joystick: Steps to reproduce

1. Set Password which contains special characters.
2. Logout
3. Try to login
4. Aaaand... broken...

**Comment by Dudrie** [comment]
That's actually fixed but the update is not on the live server yet. Your password is saved correctly, however the authorization header gets messed up by the library used.

Same problem as #87.

**Comment by Dudrie** [comment]
Follow up question: Is your password longer than 72 bytes?

**Comment by schurpl** [comment]
No.
