### ISSUE TITLE
Excel file export uses wrong days for student presence

### ISSUE THREAD

**Issue by BlockWorker** [Dudrie/Tutor-Management-System#128]
When exporting the TMS data as an Excel file (download button on the dashboard), the exported table contains the wrong weekdays (tuesday instead of wednesday for me) in the presence ("Anwesenheiten") table, which are filled with "N/A" entries instead of the actual data for the corresponding week.

Can't provide more general information for bug reproduction (as I only have access to my tutor account), but have attached the generated file (personal data censored):
[Tutorium_Mi04.xlsx](https://github.com/Dudrie/Tutor-Management-System/files/3761514/Tutorium_Mi04.xlsx)

**Comment by Dudrie** [comment]
This is due to timezones and stuff. That definitly needs some revisit and general fixing. The tutor times (clock) on the dashboards are off, too (see #130).

**Comment by Dudrie** [comment]
Got fixed in #146.

**Comment by Dudrie** [comment]
Apparently this bug still persists in the live version.
