### ISSUE TITLE
NODE_ENV not set correctly in production image

### ISSUE THREAD

**Issue by Dudrie** [Dudrie/Tutor-Management-System#136]
# 🎫 Description
The `NODE_ENV` variable is not set to `production` inside the production image. This leads to debug messages being saved in the log file(s).

**Comment by spethso** [comment]
You can take a look on https://www.npmjs.com/package/dotenv for environment variables provided in a .env file.

**Comment by Dudrie** [comment]
It's less a problem of "how to set it" more of "I forgot to include that one in the Dockerfile".
