### ISSUE TITLE
Abfrage für Scheinstatus soll Laden der Studis nicht blocken

### ISSUE THREAD

**Issue by marfraTUC** [Dudrie/Tutor-Management-System#156]
Die Übersicht aller Studenten läd sehr lange....

**Comment by marfraTUC** [comment]
und es fehlt eine Suche ;)

**Comment by Dudrie** [comment]
> Die Übersicht aller Studenten läd sehr lange....

Das ist, weil das TMS warten muss, bis der Server für alle Studis den Scheinstatus berechnet hat.

> und es fehlt eine Suche ;)

Kommt noch, wenn ich die ganzen Fixes und die Unit-Tests fertig habe.

**Comment by marfraTUC** [comment]
Der Grund ist mir klar ;)
Die Lösung wäre, die Studies anzuzeigen ohne die Berechnung und die Nachzuladen?

**Comment by Dudrie** [comment]
Ja, das ist die angepeilte Lösung. Eine Ladeanimation haben die Studibalken ja schon.

**Comment by Dudrie** [comment]
Die Suche hat jetzt ein eigenes Issue: #158.
