### ISSUE TITLE
Something is very wrong with the dates in the system - Noticed in "Vertretung"

### ISSUE THREAD

**Issue by marfraTUC** [Dudrie/Tutor-Management-System#157]
# ⚡ Actual behaviour 

* I pickt Uwes tutorium Mi6 and set myself as proxy for the 30th of november. 
* I prest save
* the system confirmed and returned to the overview
* now it says I am proxy on the 29th of November ?!
* I do not see Students in the attandence list.

**Comment by Dudrie** [comment]
Fixed in #146 but not in a production release yet (only in a pre-release).
