### ISSUE TITLE
Dateiendung der Zip der Bewertungen fehlt

### ISSUE THREAD

**Issue by PlurioLarus** [Dudrie/Tutor-Management-System#164]
Wenn man sich die PDFs von der Bewertung erstellen lässt, bekommt man eine Datei ohne Dateiendung. Man muss per Hand .zip anhängen, um sie zu benutzen.

**Comment by Dudrie** [comment]
Welchen Browser benutzt du?

**Comment by PlurioLarus** [comment]
Firefo

**Comment by Dudrie** [comment]
Als Fix, bis das im TMS gefixt ist, kannst du folgendes probieren: In den Einstellungen aktiviere "Jedes Mal nachfragen, wo eine Datei gespeichert werden soll" unter "Dateien und Anwendungen > Downloads". Der Speicherndialog fügt dann die richtige Endung automatisch hinzu.
