### ISSUE TITLE
Markdown Vorschau vs PDF

### ISSUE THREAD

**Issue by TheMrPhantom** [Dudrie/Tutor-Management-System#168]
Die Markdown-Vorschau der Abgaben entspricht nicht dem exportierten PDF

# :heavy_check_mark: Expected behaviour

Ich drücke auf Markdown-Vorschau bei den Bewertungen und sehe etwas, ich exportiere es in ein PDF und sehe das gleich in PDF form
# ⚡ Actual behaviour 

Ich drücke auf Markdown-Vorschau bei den Bewertungen und sehe etwas, ich exportiere es in ein PDF, es sieht anders aus. Z.B. keine Zeilenumbrüche.

**Comment by Dudrie** [comment]
Siehe #166. Gibt es mehr Unterschiede, die dir aufgefallen sind als fehlende Zeilenumbrüche?

**Comment by Dudrie** [comment]
Das ist vsl. in #167 gefixt, außer es gibt mehr Unterschiede als fehlende Zeilenumbrüche.

**Comment by TheMrPhantom** [comment]
Bis jetzt ist mir nichts weiteres aufgefallen

**Comment by Dudrie** [comment]
Dann schließe ich das Issue. Sollte dir noch was auffallen kannst du entwender ein neues oder dieses wieder aufmachen :smile:
