### ISSUE TITLE
Falsche Bestandens Anzeige

### ISSUE THREAD

**Issue by TheMrPhantom** [Dudrie/Tutor-Management-System#178]
In der Studentenübersicht wird falsch berechnet, wie viele Blätter bestanden wurde

**Comment by Dudrie** [comment]
Passt die Bestandensanzeige mitlerweile? Ggf. waren im System die falschen Prozentwerte hinterlegt.

**Comment by TheMrPhantom** [comment]
Es sieht so aus als wären die jetzt richtig
