### ISSUE TITLE
CSV Export in Students Overview loads forever

### ISSUE THREAD

**Issue by marfraTUC** [Dudrie/Tutor-Management-System#195]
CSV Export in Students Overview loads forever...

# :heavy_check_mark: Expected behaviour

When trying to export the students overview to csv there is a loading icon but it never finishes. 

# ⚡ Actual behaviour 

After clicking the button it should provide a .csv file to download

# :joystick: Steps to reproduce

1. Go to student overview
2. click on csv file
3. wait
4. Aaaand... broken...

**Comment by marfraTUC** [comment]
btw. it would be nice only to export the current selection as well. So if I search for something I only what to export the current result

**Comment by Dudrie** [comment]
Related to #234 and closed by #235. 

Only exporting a selection got moved into a seperate issue #236
