### ISSUE TITLE
Punktefeld für Aufgabe

### ISSUE THREAD

**Issue by TheMrPhantom** [Dudrie/Tutor-Management-System#199]
# :ticket: Description

Ein Feld bei dem man Punkte abziehen kann, die nicht speziell einer Teilaufgabe zuzuweisen sind, sondern der ganzen Aufgabe z.B wenn Doku bei Programmieraufgaben fehlt, muss man das immer von Teilaufgabe zu Teilaufgabe Copy pasten

**Comment by nk-coding** [comment]
Currently not really compatible with the data model
