### ISSUE TITLE
Verschiedene Punktzahlen für selbes Team speichert nicht

### ISSUE THREAD

**Issue by jad25** [Dudrie/Tutor-Management-System#213]
Das Menü unter "Punkte verwalten", bei dem man die Punkte einzeln für die verschiedenen Teammitglieder eintragen kann, speichert nicht. Ich kann Punkte eintragen, auf Speichern klicken und bekomme auch Rückmeldung, dass gespeichert wurde. In der Studierendenübersicht haben aber weiterhin beide die selbe Punktzahl. Getestet an meinem Macbook unter Catalina und an den Pool-PCs.

**Comment by Dudrie** [comment]
Fixed #210.
