### ISSUE TITLE
Strg + S zum speichern in der Korrekturübersicht

### ISSUE THREAD

**Issue by TheMrPhantom** [Dudrie/Tutor-Management-System#214]

**Comment by Dudrie** [comment]
#211 implementiert die Funktion, dass man im Kommentarfeld Strg + Enter zum Speichern nutzen kann. In den Punktefeldern selbst reicht ein einfaches Enter drücken, wie in anderen Webformularen.

Soll Strg + S dann noch zusätzlich hinzugefügt werden oder reicht Strg + Enter?

**Comment by TheMrPhantom** [comment]
Ich persönlich drücke immer aus Gewohnheit bzw. Reflex auf STRG S und im Moment öffnet sich dann der Dialog zum Website runterladen, was den Workflow für mich schon beeinträchtigt, also Strg S zusätzlich wäre gut

**Comment by Dudrie** [comment]
Dann füge ich Strg + S noch hinzu. Das wird dann beim Eintragen der Punkte für die Übungsblätter und die Scheinklausur funktionieren. 

Wenn es sonst noch sinnvolle Tastenkürzel gibt, kann man sich überlegen, ob man die nicht auf eine Liste packt und ggf. nach und nach implementiert.
