### ISSUE TITLE
In Firefox is the last row of lists out of sight \ frame

### ISSUE THREAD

**Issue by marfraTUC** [Dudrie/Tutor-Management-System#77]
In Firefox is the last row of lists out of sight \ frame

If you have a long list. Like tutorlists then in firefoxe there is the last row of content not visible on the screen. You can scroll down, however only the second last item is within the scrollable screen. 
![Screenshot 2019-10-15 at 10 05 37](https://user-images.githubusercontent.com/18349345/66812531-5d591300-ef33-11e9-8c0d-fbd2497a1a41.png)

**Comment by marfraTUC** [comment]
In chrome, brave it works.

**Comment by Dudrie** [comment]
It seems that Firefix handle `height: 100%` inside a flex layout in a different way than chromium based browsers (like chrome, brave, ...).

Maybe this might be an issue with other non-chromium browsers aswell (ie Safari)?
