### ISSUE TITLE
Mehrzeilige Bewertung

### ISSUE THREAD

**Issue by TheMrPhantom** [Dudrie/Tutor-Management-System#86]
# :mag_right: Short

Das Bewertungsfeld ist zu klein
# :ticket: Description

Bitte das Bewertungsfeld für die studis mehrzeilig machen und pro Aufgabe ein Textfeld

**Comment by Dudrie** [comment]
Das Feld ist mehrzeilig, es vergrößert sich bei Bedarf automatisch. Eventuell wäre es besser gewesen, wenn man das Feld direkt 2 Zeilen groß gemacht hätte, sodass man das besser erkennt 😄 

> wenn ich das richtig sehe kann man in das Feld auch Markdown schreiben?
Ja, in das Feld kann man Markdown schreiben.

**Comment by TheMrPhantom** [comment]
Ja damit wäre da Issue theoretisch hinfällig

**Comment by Dudrie** [comment]
Jaein. Was meinst du mit

> und pro Aufgabe ein Textfeld

Es gibt pro "große" Aufgabe ein Textfeld. Willst du eins pro Teilaufgabe? :)

**Comment by TheMrPhantom** [comment]
Habe da 2 Themen gemischt, habe das in #96 mal getrennt
