### ISSUE TITLE
Use monospace font in the Markdown comment text area for assigning points

### ISSUE THREAD

**Issue by kjuli** [Dudrie/Tutor-Management-System#862]
# :ticket: Description
When writing in Markdown, it is very hard to see how the text is aligned. Especially when writing code, this can become very stressful to re-align:

<img width="609" alt="Bildschirmfoto 2020-12-12 um 16 56 31" src="https://user-images.githubusercontent.com/14034899/101988677-63fc2b00-3c9b-11eb-8e47-15427477579f.png">
And the result:
<img width="640" alt="Bildschirmfoto 2020-12-12 um 16 56 58" src="https://user-images.githubusercontent.com/14034899/101988688-74aca100-3c9b-11eb-97b8-3eeb4bc1a4cc.png">

I would instead suggest to use a monospace font in that text-area. It is much clearer and more intuitive to write code snippets without re-aligning it constantly. Also, maybe using a good monospace font that also is good to read for non-code.

<img width="614" alt="Bildschirmfoto 2020-12-12 um 16 57 46" src="https://user-images.githubusercontent.com/14034899/101988706-a4f43f80-3c9b-11eb-9de4-92d27860c6fd.png">
<img width="671" alt="Bildschirmfoto 2020-12-12 um 16 58 09" src="https://user-images.githubusercontent.com/14034899/101988711-a9205d00-3c9b-11eb-9e78-2f5e152b7d03.png">

**Comment by Dudrie** [comment]
Maybe [Roboto Mono](https://fonts.google.com/specimen/Roboto+Mono) would be a good fit due to the rest of the application using the standard [Roboto](https://fonts.google.com/specimen/Roboto) font?

**Comment by kjuli** [comment]
> Maybe [Roboto Mono](https://fonts.google.com/specimen/Roboto+Mono) would be a good fit due to the rest of the application using the standard [Roboto](https://fonts.google.com/specimen/Roboto) font?

I think this would be a good choice since it perfectly fits to the rest.
