### ISSUE TITLE
scharfes S (ß) in Benutzernamen

### ISSUE THREAD

**Issue by stiesssh** [Dudrie/Tutor-Management-System#87]
Ich konnte mich unter dem Benutzernamen "stießsh" nicht einloggen, unter "stiesssh" (kein scharfes S) ging dies jedoch. Daher die Vermutung, dass "ß" in Benutzernamen nicht funktionieren.

**Comment by marfraTUC** [comment]
auch andere Umlaute klappen nicht: ä,ü,...

**Comment by Dudrie** [comment]
Der Generator für die Nutzernamen sollte aus Umlauten ihre normalen Formen, also ä -> ae, ß -> ss, machen... Genauso sollten Apostrophe entfernt werden, also è -> e

Also sollte der Nutzername 'stießsh' vom System gar nicht generiert werden, falls doch, ist das ein Bug.

Beim Erstellen der Nutzers kann man den Nutzernamen aber zur Not noch manuell anpassen (oder nach Umsetzung von #93 auch beim Bearbeiten) und da sollten Umlaute gehen, oder?

**Comment by marfraTUC** [comment]
Hauptsächlich sollte es nicht zu Fehlern kommen ;)

Aktuell ist es so, dass der Generator die Umlaute nicht abändert. Entweder es werden Umlaute unterstützt oder es sollte gar nicht möglich sein in das Usernamefeld Umlaute einzugeben.

**Comment by Dudrie** [comment]
Stimmt, der Generator ändert das nicht. Eventuell macht die Verschlüsselungsbibliothek was kaputt. Muss auf jeden Fall gefixt werden :)

**Comment by Dudrie** [comment]
TL;DR: Umlaute und andere Charaktere sollten jetzt funktionieren. 

Das Problem lag an der Bibliothek, die die Request ausführt, die hat den Header für die Authentifizierung nicht richtig kodiert (sie hat UTF-8 nicht explizit gesetzt). Mit dem nächsten Update gehen dann auch Umlaute und alle UTF-8 Sonderzeichen in Nutzernamen (und Passwörtern - die funktionieren aktuell entsprechend auch nicht mit Sonderzeichen ...).
